* tinydis

A tiny discusstion plugin without need to login, implented by leptos 


** dev

#+begin_src bash
cargo install cargo-leptos --locked
cargo leptos watch
#+end_src


** useage 

#+begin_src bash
cargo leptos build --release

cargo leptos build -r && mv target/site/assets/tinydis.wasm  target/site/assets/tinydis_bg.wasm && cp -r ./target/site/assets/ ~/note/static/ && cp -r ./target/site/assets/* ~/repos/windancer_main/public/assets/
#+end_src



Will generate your server binary in target/release and your site package in target/site

## Testing Your Project
```bash
cargo leptos end-to-end
```

```bash
cargo leptos end-to-end --release
```

Cargo-leptos uses Playwright as the end-to-end test tool.
Tests are located in end2end/tests directory.

## Executing a Server on a Remote Machine Without the Toolchain
After running a `cargo leptos build --release` the minimum files needed are:

1. The server binary located in `target/server/release`
2. The `site` directory and all files within located in `target/site`

Copy these files to your remote server. The directory structure should be:
```text
tinydis
site/
```
Set the following environment variables (updating for your project as needed):
```sh
export LEPTOS_OUTPUT_NAME="tinydis"
export LEPTOS_SITE_ROOT="site"
export LEPTOS_SITE_PKG_DIR="pkg"
export LEPTOS_SITE_ADDR="127.0.0.1:3000"
export LEPTOS_RELOAD_PORT="3001"
```
Finally, run the server binary.

