name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Verify rustup and WASM target
      run: |
        rustup --version
        rustup target list --installed | grep wasm32-unknown-unknown

    - name: Install cargo-leptos
      run: cargo install --locked cargo-leptos

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      
    - name: Build
      run: |
        cargo leptos build --release
        mv target/site/assets/tinydis.wasm  target/site/assets/tinydis_bg.wasm
        rm -rf ./target/site/assets/*.ts
